### ISSUE TITLE
JSON filter only works for a limited set of fields

### ISSUE THREAD

**Issue by mpburtt** [figueiredorui/1-click-child-links#49]
It appears that the JSON filter feature only works for the fields listed in the sample JSON shown in the markdown file...

- "System.BoardColumn"
- "System.BoardLane"
- "System.State"
- "System.Title"
- "System.WorkItemType"
- "System.Tags"

For example, {"applywhen":[{"System.WorkItemType":"User Story","Microsoft.VSTS.Common.Priority":"2"}]} always results in a child work item being created for a user story regardless of the value of the priority field.

It would be much better if it could be made to support all possible fields, including custom process fields.

**Comment by figueiredorui** [comment]
Fixed on v0.11.1

**Comment by mpburtt** [comment]
> Fixed on v0.11.1

@figueiredorui I have v0.11.2 but still have the same problem. Looking at your code here I can't see any change that would have fixed the problem either.
![image](https://user-images.githubusercontent.com/19573619/84020591-f6351680-a97a-11ea-906f-5e81cd23c50f.png)

**Comment by figueiredorui** [comment]
Hi @mpburtt , I believe is fixed now!

**Comment by Alexandre540** [comment]
Hello @figueiredorui , As @mpburtt I tried to setup the priority as filter but it doesn't work.
Here my setup :  {"applywhen":[{"System.WorkItemType":"User Story", "Microsoft.VSTS.Common.Priority":"2", "System.State":"Active"}]}

This setup without Priority works :  {"applywhen":[{"System.WorkItemType":"User Story", "System.State":"Active"}]}

**Comment by figueiredorui** [comment]
Hi @Alexandre540, should be fixed now!

**Comment by Alexandre540** [comment]
Hi @figueiredorui , Thanks for your new fix but it still doesn't work. 
Did you test this setup ? 
{"applywhen":[{"System.WorkItemType":"User Story", "Microsoft.VSTS.Common.Priority":"2", "System.State":"Active"}]}
Thank you for your help

**Comment by figueiredorui** [comment]
Hi @Alexandre540,
I have added some trace to the DevTools console and tested your setup and here is my trace.
`
1-Click Child-Links: init v0.11.11

1-Click Child-Links: template: 'Task 1'
1-Click Child-Links: filter: '{"applywhen":[{"System.WorkItemType": "User Story", "Microsoft.VSTS.Common.Priority": "2", "System.State": "Active"}]}'
1-Click Child-Links:  - filter['System.WorkItemType'] : 'User Story' - wit['System.WorkItemType'] : 'User Story' equal ? true
1-Click Child-Links:  - filter['Microsoft.VSTS.Common.Priority'] : '2' - wit['Microsoft.VSTS.Common.Priority'] : '2' equal ? true
1-Click Child-Links:  - filter['System.State'] : 'Active' - wit['System.State'] : 'Active' equal ? true
`

**Comment by Alexandre540** [comment]
Hi @figueiredorui . Thanks for this update, it works now !!
